#!/bin/bash

logs="logs"


cmd=${2}
if $(echo ${cmd} | grep -q "^SBATCH="); then
  override=$(echo ${cmd} | cut -f 2 -d '"')
  cmd=$(echo ${cmd} | cut -f 3- -d '"')
fi

declare -A args
for item in ${SBATCH} ${override}; do
  key=$(echo ${item} | cut -f 1 -d '=')
  val=$(echo ${item} | cut -f 2 -d '=')
  args[${key}]=${val}
done

for key in ${!args[*]}; do
  sbatch=$(echo -e "#SBATCH ${key}=${args[${key}]}\n${sbatch}")
done

mkdir -p ${logs}

cat << EOF | sbatch --wait
#!/bin/bash
#SBATCH --output=${logs}/%j.out
#SBATCH --error=${logs}/%j.err
${sbatch}

${cmd}

EOF
